# Generated by Django 5.2.13 on 2026-04-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('unidade_medida', models.CharField(max_length=20, verbose_name='Unidade de Medida')),
                ('preco_atual_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço atual por KG')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='ProducaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_bruto_utilizado', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Peso Bruto (kg)')),
                ('marmitas_produzidas', models.IntegerField(verbose_name='Marmitas Produzidas')),
                ('custo_por_marmita_calculado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo por Marmita')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Produção Diária',
                'verbose_name_plural': 'Produções Diárias',
            },
        ),
    ]
